name: Morning Notification
on:
  schedule:
    - cron: '0 23 * * *' # This is 7am SGT (UTC+8)
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: "Daily Briefing: 7:00 AM"
          body: "Good morning! Check your dashboard for today's tasks."
          to: your-email@example.com
